apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres_main
    orgId: 1
    url: dlh-postgres:5432
    database: ${POSTGRES_DB:-datalakehouse}
    user: ${POSTGRES_USER:-dlh_admin}
    access: proxy
    isDefault: false
    jsonData:
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
    secureJsonData:
      password: ${POSTGRES_PASSWORD:-}
    version: 1
    editable: true
